"use strict";
let  cloth = document.querySelector("svg");
let clockCircle = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
clockCircle.setAttribute("cx", "200");
clockCircle.setAttribute("cy", "200");
clockCircle.setAttribute("r", "200");
clockCircle.setAttribute("fill", "aqua");
cloth.appendChild(clockCircle);

const num = 12;
const arc = 2 * Math.PI * (1/num);
const radius = 170;
 for(let i = 0; i < num; i++ ){
     let miniCircle = document.createElementNS('http://www.w3.org/2000/svg', "circle");
     const angle = i * arc;
     const x = radius * Math.cos(angle-1) + 200;
     const y = radius * Math.sin(angle-1) + 200;
     miniCircle.setAttribute("cx", `${Math.round(x)}`);
     miniCircle.setAttribute("cy", `${Math.round(y)}`);
     miniCircle.setAttribute("r", `25`);
     miniCircle.setAttribute("fill", `red`);
     let clockNumber = document.createElementNS('http://www.w3.org/2000/svg', "text");
     cloth.appendChild(miniCircle);
     clockNumber.innerHTML = i+1;
     clockNumber.setAttribute("x", `${Math.round(x)}`);
     clockNumber.setAttribute("y", `${Math.round(y)}`);
     cloth.appendChild(clockNumber);
 }
let hourHand = document.createElementNS('http://www.w3.org/2000/svg', "line");
hourHand.setAttribute("x1", "200");
hourHand.setAttribute("y1", "200");
hourHand.setAttribute("x2", "200");
hourHand.setAttribute("y2", "100");
hourHand.setAttribute("stroke", "black");
hourHand.setAttribute("stroke-width", "5");
let minuteHand = document.createElementNS('http://www.w3.org/2000/svg', "line");
minuteHand.setAttribute("x1", "200");
minuteHand.setAttribute("y1", "200");
minuteHand.setAttribute("x2", "200");
minuteHand.setAttribute("y2", "60");
minuteHand.setAttribute("stroke", "black");
hourHand.setAttribute("stroke-width", "3");
let secondHand = document.createElementNS('http://www.w3.org/2000/svg', "line");
secondHand.setAttribute("x1", "200");
secondHand.setAttribute("y1", "200");
secondHand.setAttribute("x2", "200");
secondHand.setAttribute("y2", "70");
hourHand.setAttribute("stroke-width", "2");
secondHand.setAttribute("stroke", "red");
let anim = document.createElementNS('http://www.w3.org/2000/svg', "animateTransform");4
anim.setAttribute("attributeName", "transform");
anim.setAttribute("type", "rotate");
anim.setAttribute("repeatCount", "indefinite");
anim.setAttribute("dur", "60s");
anim.setAttribute("by", "360");
cloth.appendChild(hourHand);
cloth.appendChild(minuteHand);
cloth.appendChild(secondHand);
 setInterval(()=>{
     let date = new Date();
     let h = parseInt(date.getHours());
     h = h > 12 ? h-12: h;
     let m = parseInt(date.getMinutes());
     let s = parseInt(date.getSeconds());
     let second = 6*s;
     let minute =(m+s/60)*6;
     let hour = (h+m/60+s/3600)*30;
     hourHand.setAttribute("transform",`rotate(${hour})`);
     minuteHand.setAttribute("transform",`rotate(${minute})`);
     secondHand.setAttribute("transform",`rotate(${second})`);
 }, 1000);
